### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by boryssmejda** [boryssmejda/VHDL_PROJECT_CPLD#1]
- [x] Finish and test stop watch without a MUX
- [x ] Finish and test stop watch using MUX concept
- [ ] Add stopping and starting the timer by using a simple button - (one for start/stop or two different, does not matter)
- [ ] Add keypad functionality to set the time from which to count down
